### PR TITLE
Deny all statement should specify not_actions

### LINKED ISSUE #1: Bug in manage_explicit_deny ?
## Bug Report

While reviewing the changes from the last commit (https://github.com/terraform-module/terraform-aws-enforce-mfa/commit/0e7b8298ea5d5a554871c331f1943ee7db118a29), I notice that the following group of "not_actions" 

```
  statement {
    sid    = "BlockMostAccessUnlessSignedInWithMFA"
    effect = "Deny"
    not_actions = [
      "iam:CreateVirtualMFADevice",
      "iam:DeleteVirtualMFADevice",
      ...
    ]
    resources = ["*"]
    condition {
      test     = "BoolIfExists"
      variable = "aws:MultiFactorAuthPresent"
      values   = ["false", ]
    }
  }
```

became "actions" in the refactor:

```
  dynamic "statement" {
    for_each = var.manage_explicit_deny ? [1] : []

    content {
      sid    = "DenyAllExceptListedIfNoMFA"
      effect = "Deny"
      actions = [
        "iam:CreateVirtualMFADevice",
        "iam:EnableMFADevice",
        ...
      ]
      resources = ["*"]
      condition {
        test     = "BoolIfExists"
        variable = "aws:MultiFactorAuthPresent"
        values   = ["false", ]
      }
    }
  }
```
These should be written as "not_actions" right?

### PR DESCRIPTION
**Pull request by vsimon**
Fixes #1

### CODE REVIEW

**Comment by eschultink** [comment]
+1 seems like you fixed this on your own fork, but it is still broken on master at https://github.com/terraform-module/terraform-aws-enforce-mfa/releases/tag/v0.12.6 - can you re-open?

**Comment by vsimon** [comment]
Sure!

**Comment by eschultink** [comment]
@ivankatliarchuk would be great to get this merged. It solves #1, which otherwise seems to still affect v0.12.6 of the module:  our config uses the module with `manage_explicit_deny = true` causing it to generate a IAM policy statement that matches the canonical one from AWS MFA documentation, except it uses `Action` rather than `NotAction`.

**Comment by ivankatliarchuk** [comment]
Apologies seems like have a notificaiton broken on my side

**Pull request merged**
